###
POST http://localhost:5000//UserInfo HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "EventID":"1",
    "Name":"김나성",
    "CarType":"value2", 
    "CarNumber":"15누-8762"
}

###
POST http://localhost:5000//ParkingSpace HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "EventID":"2",
    "ParkingSpace":2, 
    "CarNumber":"15누-8762"
}

###
POST http://localhost:5000//TurnOff HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "EventID":"4",
    "CarNumber":"15누-8762"
}

###
GET http://localhost:5000//get-json-data
    ?EventID=3
Content-Type: application/json; charset=UTF-8
###


